{{- if .Values.kafka.externalAccess.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ingress
  namespace: kafka

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  kafka-controller-0-external
                port:
                  number: 9094
{{- end }}