{{- if .Values.submitServiceAccount.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.submitServiceAccount.token }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.submitServiceAccount.name }}
type: kubernetes.io/service-account-token
{{- end }}