{{- if .Values.submitServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bigDataSpark.submitServiceAccount.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}