kafka:
  controller:
    replicaCount: 2
  broker:
    replicaCount: 0
  
  externalAccess:
    enabled: true
    controller:
      service:
        type: ClusterIP
        ports:
          external: 9094
          domain: 172.29.17.2
        
