kafka:
  extraConfig:
    logRetentionHours: 1

  controller:
    replicaCount: 3
  broker:
    replicaCount: 0
  
  externalAccess:
    enabled: true
    controller:
      service:
        type: NodePort
    autoDiscovery:
      enabled: true

  serviceAccount:
    create: true
  rbac:
    create: true
  
