kafka:
  extraConfig: |
    log.retention.hours=1

  controller:
    replicaCount: 3
  broker:
    replicaCount: 0
  
  externalAccess:
    enabled: true
    controller:
      service:
        type: LoadBalancer
      containerPorts:
        external: 9094
    autoDiscovery:
      enabled: true

  serviceAccount:
    create: true
  rbac:
    create: true
  
