kafka:
  extraConfig: |
    log.retention.hours=1

  controller:
    replicaCount: 3
  broker:
    replicaCount: 0
  
  externalAccess:
    enabled: true
    controller:
      service:
        type: ClusterIP
        ports:
          external: 9094

  serviceAccount:
    create: true
  rbac:
    create: true
  
